### ISSUE TITLE
Patch for missing AI_NUMERICSERV: possible to add?

### ISSUE THREAD

**Issue by barracuda156** [shikokuchuo/nanonext#9] opened 2023-04-19 22:17 UTC
Could we add this somehow? https://github.com/nanomsg/nng/pull/1651
Since `nanonext` downloads the source, I cannot patch it prior to installation.

**Comment by shikokuchuo** [comment] 2023-04-20 07:34
I see your PR got merged so it will make it into the next release. I will update the bundled NNG source to the latest even if NNG 1.6.0 is not available by then (but which I hope will be the case).

Btw. the source is bundled (located in "/inst" as a tar.xz), not downloaded.

**Comment by shikokuchuo** [comment] 2023-04-24 19:44
Note: this patch is already incorporated in the bundled source as of [d2d72d9](https://github.com/shikokuchuo/nanonext/commit/d2d72d9c9013d32902ce01f211a6c3f43dda132d).

**Comment by barracuda156** [comment] 2023-04-24 20:21
@shikokuchuo Great!

**Comment by shikokuchuo** [comment] 2023-05-25 18:39
The bundled 'libnng' version is being rolled back to 831816f prior to this patch  due to regressions. Will have to wait for Garrett D'Amore to provide a new beta / release.

**Comment by barracuda156** [comment] 2023-05-25 18:45
> The bundled 'libnng' version is being rolled back to 831816f prior to this patch due to regressions. Will have to wait for Garrett D'Amore to provide a new beta / release.

Thank you for letting me know.

**Comment by barracuda156** [comment] 2023-05-29 05:36
@shikokuchuo So 0.9.0 will be broken, right?

**Comment by shikokuchuo** [comment] 2023-05-29 08:00
Not at all. It is in fact compatible with existing released NNG now, so you are not forced to use the bundled version. If you have a system patched NNG 1.5.2 it will work. When NNG 1.6.0 is released, the bundled version will be updated.

**Comment by shikokuchuo** [comment] 2023-05-29 08:19
Closing as it is for @gdamore to provide the next NNG library version, where this ultimately will either be addressed or not.

**Closed** 2023-05-29 08:19 UTC

**Comment by barracuda156** [comment] 2023-05-29 12:29
@shikokuchuo It builds, but fails to load:
```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘nanonext’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-nanonext/R-nanonext/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/00LOCK-nanonext-0.9.0/00new/nanonext/libs/nanonext.so':
  dlopen(/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-nanonext/R-nanonext/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/00LOCK-nanonext-0.9.0/00new/nanonext/libs/nanonext.so, 6): Symbol not found: _nng_tls_config_hold
  Referenced from: /opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-nanonext/R-nanonext/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/00LOCK-nanonext-0.9.0/00new/nanonext/libs/nanonext.so
  Expected in: dynamic lookup

Error: loading failed
Execution halted
```

**Comment by barracuda156** [comment] 2023-06-01 15:49
@shikokuchuo Any idea why this may not be working?

**Comment by shikokuchuo** [comment] 2023-06-01 15:59
It may be a packaging issue. If the macports `libnng` was not built against `libmbedtls`.

**Comment by barracuda156** [comment] 2023-06-01 16:02
> It may be a packaging issue. If the macports `libnng` was not built against `libmbedtls`.

Thank you for a hint, apparently it is not: https://ports.macports.org/port/nng/details
I was using `libmbedtls` for your `nng` package directly.

I will look into fixing this.

**Comment by barracuda156** [comment] 2023-06-01 21:34
@shikokuchuo You were right, enabling `libmbedtls` in `nng` fixed the build on `nanonext`.
